version: '3.8'

services:
  web:
    build: .
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./scripts/run_migrations.sh && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  test:
    build: .
    command: pytest --cov=app
    volumes:
      - ./:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - db
      - web

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env

volumes:
  postgres_data:
